### ISSUE TITLE
 [System.NullReferenceException] not debuggable

### ISSUE THREAD

**Issue by jcrecio** [hector-co/Qurl#1]
Hi there :)

Just trying it but I'm getting
{
  "fault": {
    "code": 0,
    "text": "Object reference not set to an instance of an object. [System.NullReferenceException]"
  }
}

and there is no way to debug more.

Just a simple project, with a model 
```
    public class CustomFilter
    {
        public FilterProperty<int> Prop1 { get; set; }
        public FilterProperty<int> Prop2 { get; set; }
        public FilterProperty<string> Prop3 { get; set; }
}
```

It's registered at startup (after addMvc() )
`services.AddQurlModelBinder();`

and the controller 
```
  public async Task<Dto> Find([FromQuery] Query<CustomFilter>){
 // it never hits here with a breakpoint
}
```

url: base/action?Prop1=1&Prop2=2&Prop3=three

Sorry for the update but the example of the own documentation does not work neither:
```
var queryString = "id[gt]=2&title[ct]=testTitle&active=true";
var query = QueryBuilder.FromQueryString<Query<SampleDtoFilter>>(queryString);
```

**Comment by hector-co** [comment]
Hi there,

There was an issue related to the default mode selected, it was fixed in this [commit](https://github.com/hector-co/Qurl/commit/db45fccf8d508ad61834e2eece3a42d6c4412d6b), that was causing an exception, also with the last piece of code that you mention.
The example application it's working fine right now (migrations needs to be run manually), you can verify the functionality there.
